#!/bin/bash

#curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable -y
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
echo '. $HOME/.cargo/env' >> ~/.bashrc
echo '. $HOME/.cargo/env' >> ~/.profile
source $HOME/.cargo/env

cargo install evcxr_jupyter
evcxr_jupyter --install
